name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build the server
        run: ./gradlew --info clean build
